# Generated by Django 4.2.1 on 2023-05-26 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_categories', '0001_initial'),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('ELECTRONICS', 'Electronics'), ('LIFE_STYLE', 'Life_Style'), ('MOBILE_PHONE_ACCESSORIES', 'Mobile_Phone_Accessories')], max_length=100, null=True, verbose_name='Type')),
                ('warranty', models.CharField(max_length=255, null=True, verbose_name='Warranty')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_brands', to='product_categories.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_categories', to='product_categories.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_seller', to='sellers.seller')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
